; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env]
board_build.filesystem = littlefs
build_flags =
        '-Wall'
	'-Wno-deprecated'
lib_deps =
	bakercp/CRC32@^2.0.0
	bblanchon/ArduinoJson@^7.0.0
	nanopb/Nanopb
lib_ldf_mode = deep+
lib_archive = no
check_tool = clangtidy

[env:native]
platform = native
lib_archive = no
build_flags =
	${env.build_flags}
	'-DNATIVE'
	-I include
	-I src/og3_include
lib_deps =
	fabiobatsilva/ArduinoFake
	symlink://../og3
	${env.lib_deps}
	unity
lib_ignore =
	PsychicMqttClient
	PsychicHttp
	ESPAsyncWebServer-esphome
	ESPAsyncWebServer
	AsyncMqttClient-esphome
	AsyncMqttClient
	ESPAsyncTCP
	Hash
lib_compat_mode = off
test_build_src = yes
build_src_filter = +<src/*> -<src/device.pb.c> +<src/og3_src/*.cpp>
build_type = debug

[esp_base]
framework = arduino
build_src_filter = +<src/*> -<src/og3_src/*> -<src/og3_include/*>
monitor_speed = 115200
uploadProtocol = esptool
uploadPort = /dev/ttyUSB0

[esp32_base]
extends = esp_base
platform = espressif32
monitor_filters = esp32_exception_decoder
lib_deps =
	${env.lib_deps}
	elims/PsychicMqttClient@^0.2.4
	hoeken/PsychicHttp@^2.1.1

[env:d1_mini]
extends = esp_base
platform = espressif8266
board = d1_mini
monitor_filters = esp8266_exception_decoder
lib_deps =
	${env.lib_deps}
	ESP32Async/ESPAsyncWebServer@3.6.0
	heman/AsyncMqttClient-esphome@^1.0.0

[env:esp32dev]
extends = esp32_base
board = esp32dev
build_flags =
	${env.build_flags}
	'-DBLINK_LED=16'
